version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
      exclude:
        - gds-api-adapters
        - govspeak
        - govuk_*
        - rails_translation_manager
        - rubocop-govuk
        - plek

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: ruby

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
