version: 2
percy:
  useSystemProxy: false
  skipBaseBuild: false
snapshot:
  widths:
    - 375
    - 1280
  minHeight: 1024
  percyCSS: ""
  enableJavaScript: false
  cliEnableJavaScript: true
  disableShadowDOM: false
  forceShadowAsLightDOM: false
  responsiveSnapshotCapture: false
  ignoreCanvasSerializationErrors: false
  ignoreStyleSheetSerializationErrors: false
  ignoreIframeSelectors: []
  enablePseudoClassSerialization: false
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 100
  scrollToBottom: false
  captureMockedServiceWorker: false
  retry: true
  launchOptions:
    closeBrowser: true
  fontDomains: []
  autoConfigureAllowedHostnames: true
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
