C4Context
  title System Context diagram for Frontend Pages
  Person(user, "User", "A member of the public")
  System_Boundary(b0, "GOV.UK") {
    System_Boundary(b1, "GOV.UK Web Frontend") {
      System(frontend, "Frontend", "Renders pages for public")
    }
    System_Boundary(b1, "GOV.UK Web APIs") {
      System(local_links_manager, "Local Links Manager", "Stores information about Local Authorities")
      System(places_manager, "Places Manager", "Stores information about nearby services")
      System(locations_api, "Locations API", "Postcode lookup service")
    }
    System_Boundary(b2, "GOV.UK Publishing") {
      System(content_store, "Content Store", "The store for denormalised GOV.UK content.")
    }
  }

  BiRel(user, frontend, "Uses")
  Rel(frontend, content_store. "Retrieves content items")
  Rel(frontend, local_links_manager. "Retrieves links for a local authority")
  Rel(frontend, places_manager. "Retrieves places near a point")
  Rel(frontend, locations_api. "Converts postcode to place/local authority")
