name: Run Jasmine

on:
  workflow_call:

jobs:
  run-jasmine:
    name: Run Jasmine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Setup Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          bundler-cache: true

      - name: Setup Node
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@main

      - name: Run Jasmine
        run: yarn run jasmine:ci
