name: Run Jasmine

on:
  workflow_call:

jobs:
  run-jasmine:
    name: Run Jasmine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Setup Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true

      - name: Setup Node
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@main

      - name: Run Jasmine
        run: yarn run jasmine:ci
