name: Run Jasmine

on:
  workflow_call:

jobs:
  run-jasmine:
    name: Run Jasmine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          bundler-cache: true

      - name: Setup Node
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@main

      - name: Run Jasmine
        run: yarn run jasmine:ci
