on:
  push:
    branches:
      - main

jobs:
  visual-regression-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # Also runs `bundle install`
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: "12"
          cache: yarn
- run: yarn install --frozen-lockfile
- uses: percy/exec-action@v0.3.1
  with:
    command: bundle exec rake test_unit
  env:
    PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}